// Bilingual (தமிழ்/English) labels for the birth-data intake wizard only.
// This is scoped to this wizard, kept intentionally simple (a plain object,
// no framework) — see backend/src/i18n/README.md: Phase 14 builds the
// full glossary/i18n system used across the report generator. Tamil is the
// default per spec §26-27.
export type WizardLanguage = 'ta' | 'en';

export const labels = {
  ta: {
    languagePrompt: 'உங்களுக்கு எந்த மொழியில் ஜாதக அறிக்கையைப் பெற விரும்புகிறீர்கள்?',
    tamil: 'தமிழ்',
    english: 'English',
    step1Title: 'படி 1: பிறப்பு விவரங்கள்',
    step2Title: 'படி 2: பிறந்த இடம்',
    step3Title: 'படி 3: கணிப்பு அமைப்புகள்',
    name: 'பெயர்',
    gender: 'பாலினம்',
    male: 'ஆண்',
    female: 'பெண்',
    other: 'மற்றவை',
    dateOfBirth: 'பிறந்த தேதி',
    timeOfBirth: 'பிறந்த நேரம்',
    timeAccuracyQuestion: 'பிறந்த நேரம் எவ்வளவு துல்லியமானது?',
    timeAccuracy: {
      EXACT: 'மிகவும் துல்லியம்',
      WITHIN_5_MIN: 'சுமார் 5 நிமிடங்கள்',
      WITHIN_15_MIN: 'சுமார் 15 நிமிடங்கள்',
      WITHIN_30_MIN: 'சுமார் 30 நிமிடங்கள்',
      UNKNOWN: 'தெரியவில்லை',
    },
    placeSearchLabel: 'பிறந்த இடத்தைத் தேடுங்கள்',
    placeSearchPlaceholder: 'எ.கா. சென்னை, தமிழ்நாடு',
    searching: 'தேடுகிறது...',
    noResults: 'முடிவுகள் இல்லை',
    selectedPlace: 'தேர்ந்தெடுக்கப்பட்ட இடம்',
    latitude: 'அட்சரேகை (Latitude)',
    longitude: 'தீர்க்கரேகை (Longitude)',
    timezone: 'நேர மண்டலம் (Timezone)',
    utcOffset: 'UTC ஆஃப்செட் (நிமிடங்கள்)',
    dst: 'கோடை நேரம் (DST) பொருந்துமா?',
    manualCorrection: 'இடத் தகவலை கைமுறையாக திருத்தவும்',
    resolvingTimezone: 'நேர மண்டலம் கணக்கிடப்படுகிறது...',
    ayanamsaLabel: 'அயனாம்சம் (Ayanamsa)',
    ayanamsaValue: 'லாஹிரி (Lahiri) — இயல்புநிலை',
    ayanamsaNote:
      'தற்போது லாஹிரி அயனாம்சம் மட்டுமே ஆதரிக்கப்படுகிறது. இது ஒவ்வொரு ஜாதகத்திலும் பதிவு செய்யப்படும், அமைதியாக மாற்றப்படாது.',
    back: 'பின்செல்',
    next: 'அடுத்து',
    submit: 'சேமி',
    submitting: 'சேமிக்கிறது...',
    missingBirthTimeWarning:
      'பிறந்த நேரம் இல்லாததால் லக்னம் மற்றும் பாவ அடிப்படையிலான கணிப்புகளில் துல்லியம் குறையலாம்.',
    successTitle: 'பிறப்பு விவரங்கள் சேமிக்கப்பட்டன',
    computingChart: 'ஜாதகம் கணக்கிடப்படுகிறது...',
    resultsTitle: 'லக்னம், ராசி, நட்சத்திரம்',
    rasiChartTitle: 'ராசி கட்டம் (D1)',
    navamsaChartTitle: 'நவாம்ச கட்டம் (D9)',
    lagnaLabel: 'லக்னம்',
    rasiLabel: 'ராசி (சந்திர ராசி)',
    nakshatraLabel: 'நட்சத்திரம்',
    padaLabel: 'பாதம்',
    degreeLabel: 'பாகை',
    fullChartNote:
      'இந்த அட்டவணை ஜோதிட கணக்கீடுகளை மட்டுமே காட்டுகிறது. வாழ்க்கை பலன் விளக்கம் AI மூலம் அடுத்த கட்டங்களில் (Phase 13) சேர்க்கப்படும்.',
    dashaTitle: 'விம்சோத்தரி தசை',
    currentDashaLabel: 'தற்போதைய தசை',
    mahadashaLabel: 'மகாதசை',
    antardashaLabel: 'புத்தி (அந்தரம்)',
    pratyantardashaLabel: 'பிரத்யந்தரம்',
    previousMahadashaLabel: 'கடந்த மகாதசை',
    nextMahadashaLabel: 'அடுத்த மகாதசை',
    mahadashaTimelineTitle: 'மகாதசை காலவரிசை',
    toLabel: 'முதல்',
    transitTitle: 'கோச்சாரம் (Transit)',
    transitNote: 'இது இன்றைய கோச்சார நிலை — ஜாதக அடிப்படையிலான நிரந்தர பலனிலிருந்து வேறுபட்டது.',
    transitGrahaCol: 'கிரகம்',
    transitSignCol: 'ராசி',
    houseFromMoonCol: 'ராசியிலிருந்து பாவம்',
    houseFromLagnaCol: 'லக்னத்திலிருந்து பாவம்',
    sadeSatiLabel: 'சாடே சாத்தி (ஏழரை சனி)',
    sadeSatiPhase: {
      RISING: 'முதல் அடி',
      PEAK: 'உச்ச கட்டம்',
      SETTING: 'இறுதி அடி',
    },
    sadeSatiInactive: 'தற்போது பொருந்தாது',
    ashtamaShaniLabel: 'அஷ்டம சனி',
    janmaShaniLabel: 'ஜென்ம சனி',
    yesLabel: 'ஆம்',
    noLabel: 'இல்லை',
    yogaTitle: 'முக்கிய யோகங்கள்',
    noYogasFound: 'இந்த ஜாதகத்தில் கீழ்க்காணும் பட்டியலிலிருந்து யோகங்கள் எதுவும் கண்டறியப்படவில்லை.',
    yogaStrength: {
      LOW: 'மிதமான',
      MODERATE: 'நடுத்தர',
      STRONG: 'வலுவான',
    },
    yogaPlanetsLabel: 'கிரகங்கள்',
    yogaHousesLabel: 'பாவங்கள்',
    doshaTitle: 'தோஷங்கள்',
    doshaIntro:
      'கீழே பட்டியலிடப்பட்டுள்ளவை பாரம்பரிய ஜோதிட விதிகளின் அடிப்படையில் கண்டறியப்பட்ட அமைப்புகள். இவை நிர்ணயிக்கப்பட்ட தீர்ப்புகள் அல்ல — ஜோடி பொருத்தம் அல்லது பரிகாரம் தேவைப்பட்டால் தகுதியான ஜோதிடரை அணுகவும்.',
    noDoshasFound: 'இந்த ஜாதகத்தில் கீழ்க்காணும் பட்டியலிலிருந்து தோஷங்கள் எதுவும் கண்டறியப்படவில்லை.',
    doshaSeverity: {
      LOW: 'மிதமான',
      MODERATE: 'நடுத்தர',
      STRONG: 'வலுவான',
    },
    doshaRuleLabel: 'கண்டறியப்பட்ட காரணம்',
    houseAnalysisTitle: '12 பாவங்களின் விளக்கம்',
    houseCol: 'பாவம்',
    signCol: 'ராசி',
    significationCol: 'குறிக்கும் விஷயங்கள்',
    lordCol: 'அதிபதி',
    occupantsCol: 'கிரகங்கள்',
    aspectsCol: 'பார்வைகள்',
    influenceCol: 'சுப / அசுப',
    strengthCol: 'பலம்',
    conjunctionTag: 'சேர்க்கை',
    none: '—',
    beneficShort: 'சுபம்',
    maleficShort: 'அசுபம்',
    createAnother: 'மற்றொரு ஜாதகத்தை உருவாக்கு',
    requiredField: 'இந்த புலம் அவசியம்',
    error: 'பிழை',
    predictionTitle: 'AI விளக்கம்',
    predictionSectionNames: {
      basic_reading: 'ஜாதகத்தின் சுருக்கம்',
      health: 'உடல்நலம்',
      wealth: 'செல்வம் மற்றும் பணநிலை',
      career: 'தொழில்',
      marriage: 'திருமணம் மற்றும் துணை வாழ்க்கை',
      karma: 'கர்மா மற்றும் ஆன்மீக போக்கு',
      future: 'வரும் காலப் போக்கு',
      graha_phalan: 'கிரக பலன்கள்',
      past_life: 'கடந்த கால வாழ்க்கை விளக்கம்',
      present_life: 'தற்போதைய வாழ்க்கை நிலை',
      business: 'வியாபாரம்',
      family: 'குடும்பம்',
      children: 'குழந்தைகள்',
      education: 'கல்வி',
      foreign_travel: 'வெளிநாடு',
      property: 'சொத்து',
      favorable_periods: 'சாதகமான காலங்கள்',
      favorable_days: 'சாதகமான நாட்கள்',
      favorable_colors: 'சாதகமான நிறங்கள்',
      favorable_numbers: 'சாதகமான எண்கள்',
      remedies: 'பரிகாரங்கள்',
      life_timeline: 'முக்கியமான வாழ்க்கை காலவரிசை',
      final_summary: 'இறுதி சுருக்கம்',
    },
    generateButton: 'AI விளக்கம் பெறு',
    regenerateButton: 'மீண்டும் உருவாக்கு',
    generating: 'உருவாக்கப்படுகிறது... (சிறிது நேரம் ஆகலாம்)',
    predictionConfidenceLabel: 'நம்பகத்தன்மை',
    predictionConfidence: {
      HIGH: 'அதிகம்',
      MEDIUM: 'நடுத்தரம்',
      LOW: 'குறைவு',
    },
    palanPeriodLabel: 'பலன் சொல்ல வேண்டிய காலம்',
    palanPeriodMode: {
      CURRENT: 'தற்போதைய தசை/புத்தி மட்டும்',
      NEXT_YEARS: 'இத்தனை ஆண்டுகளுக்கு',
      WHOLE_LIFE: 'முழு ஆயுட்காலம்',
      UNTIL_DASHA: 'குறிப்பிட்ட தசை வரை',
    },
    palanPeriodYearsLabel: 'ஆண்டுகள்',
    palanPeriodUntilMahadashaLabel: 'இந்த மகாதசை வரை',
    palanPeriodUntilAntardashaLabel: 'இந்த அந்தரதசை வரை (விருப்பம்)',
    palanPeriodUntilAntardashaAny: 'மகாதசை முழுவதும்',
    reportStructureTitle: 'அறிக்கை கட்டமைப்பு (34 பிரிவுகள்)',
    reportStructureNote: 'ஒவ்வொரு ஜாதக அறிக்கையும் இந்த 34 பிரிவுகளைக் கொண்டது (இது இன்னும் கட்டமைக்கப்பட்டு வருகிறது).',
    reportStatus: {
      chart_data: 'கணக்கிடப்பட்டது',
      ai_generated: 'AI உருவாக்கியது',
      ai_pending: 'AI விளக்கம் இன்னும் பெறப்படவில்லை',
      unavailable: 'விரைவில்',
    },
    loadingReport: 'அறிக்கை கட்டமைப்பு ஏற்றப்படுகிறது...',
    pdfTitle: 'PDF அறிக்கை',
    pdfDownloadButton: 'PDF பதிவிறக்கு',
    pdfGenerating: 'PDF உருவாக்கப்படுகிறது... (சிறிது நேரம் ஆகலாம்)',
    pdfNote: 'PDF-இல் இதுவரை உருவாக்கப்பட்ட AI விளக்கங்கள் மட்டுமே சேர்க்கப்படும். மேலே "மீண்டும் உருவாக்கு" செய்தபின் புதிய PDF பதிவிறக்கவும்.',
    pdfEmailButton: 'மின்னஞ்சலுக்கு அனுப்பு',
    pdfEmailSending: 'அனுப்பப்படுகிறது...',
    pdfEmailSent: 'அனுப்பப்பட்டது',
    myChartsTitle: 'எனது ஜாதகங்கள்',
    noChartsYet: 'நீங்கள் இன்னும் எந்த ஜாதகமும் உருவாக்கவில்லை.',
    createFirstChartButton: 'முதல் ஜாதகத்தை உருவாக்கு',
    viewChartButton: 'ஜாதகத்தைப் பார்',
    loadingCharts: 'ஜாதகங்கள் ஏற்றப்படுகின்றன...',
    bornOnLabel: 'பிறந்த தேதி',
    backToDashboard: 'முகப்புக்குத் திரும்பு',
    loadingChart: 'ஜாதகம் ஏற்றப்படுகிறது...',
    overviewTab: 'பொதுக்கணிப்பு',
    housesTab: 'பாவகம்',
    yogasTab: 'யோகங்கள் & தோஷங்கள்',
    aiTab: 'AI விளக்கம்',
    chartDetailsTitle: 'ஜாதக விவரம்',
    downloadPdfAction: 'PDF அறிக்கை',
    settingsTitle: 'அமைப்புகள்',
    settingsAccountSection: 'கணக்கு',
    settingsEmailLabel: 'மின்னஞ்சல்',
    settingsRoleLabel: 'பங்கு',
    settingsPlanLabel: 'திட்டம்',
    settingsLanguageSection: 'இயல்புநிலை மொழி',
    settingsLanguageNote: 'இந்த சாதனத்தில் இயல்புநிலையாகக் காட்டப்படும் மொழி.',
    settingsLogoutButton: 'வெளியேறு',
    settingsDangerZone: 'ஆபத்தான பகுதி',
    settingsDeleteAccountButton: 'கணக்கை நிரந்தரமாக நீக்கு',
    settingsDeleteAccountNote: 'இது உங்கள் அனைத்து ஜாதகங்கள், அறிக்கைகள் மற்றும் கணக்குத் தரவையும் நிரந்தரமாக நீக்கும்.',
    settingsDeleteConfirmPrompt: 'உறுதியாக நீக்க வேண்டுமா? இதை மீட்டெடுக்க முடியாது.',
    settingsDeleting: 'நீக்கப்படுகிறது...',
    settingsBackToDashboard: 'முகப்புக்குத் திரும்பு',
    askAiTitle: 'ஜாதகத்திடம் கேளுங்கள்',
    askAiLanguageLabel: 'பதில் மொழி',
    askAiPlaceholder: 'எ.கா. நான் எப்போது வெளிநாடு செல்வேன்? எனக்கு எப்போது திருமணம் நடக்கும்?',
    askAiSubmit: 'கேள்வி கேள்',
    askAiAsking: 'யோசிக்கிறது...',
    askAiEmpty: 'உங்கள் ஜாதகத்தைப் பற்றி எதுவும் கேளுங்கள் — பதில் இந்த ஜாதகத்தின் கணக்கிடப்பட்ட தரவின் அடிப்படையில் மட்டும் இருக்கும்.',
    askAiHistoryTitle: 'முந்தைய கேள்விகள்',
  },
  en: {
    languagePrompt: 'Which language would you like your Jathakam report in?',
    tamil: 'Tamil',
    english: 'English',
    step1Title: 'Step 1: Birth Details',
    step2Title: 'Step 2: Birth Place',
    step3Title: 'Step 3: Calculation Settings',
    name: 'Name',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    dateOfBirth: 'Date of Birth',
    timeOfBirth: 'Time of Birth',
    timeAccuracyQuestion: 'How accurate is the birth time?',
    timeAccuracy: {
      EXACT: 'Very accurate',
      WITHIN_5_MIN: 'Within 5 minutes',
      WITHIN_15_MIN: 'Within 15 minutes',
      WITHIN_30_MIN: 'Within 30 minutes',
      UNKNOWN: 'Unknown',
    },
    placeSearchLabel: 'Search birth place',
    placeSearchPlaceholder: 'e.g. Chennai, Tamil Nadu',
    searching: 'Searching...',
    noResults: 'No results',
    selectedPlace: 'Selected place',
    latitude: 'Latitude',
    longitude: 'Longitude',
    timezone: 'Timezone',
    utcOffset: 'UTC offset (minutes)',
    dst: 'DST applicable?',
    manualCorrection: 'Manually correct location details',
    resolvingTimezone: 'Resolving timezone...',
    ayanamsaLabel: 'Ayanamsa',
    ayanamsaValue: 'Lahiri — default',
    ayanamsaNote:
      'Only Lahiri ayanamsa is supported currently. It is recorded on every chart and never changed silently.',
    back: 'Back',
    next: 'Next',
    submit: 'Save',
    submitting: 'Saving...',
    missingBirthTimeWarning:
      'Without an exact birth time, lagna- and house-based predictions may be less accurate.',
    successTitle: 'Birth details saved',
    computingChart: 'Calculating the chart...',
    resultsTitle: 'Lagna, Rasi, Nakshatra',
    rasiChartTitle: 'Rasi Chart (D1)',
    navamsaChartTitle: 'Navamsa Chart (D9)',
    lagnaLabel: 'Lagna (Ascendant)',
    rasiLabel: 'Rasi (Moon sign)',
    nakshatraLabel: 'Nakshatra',
    padaLabel: 'Pada',
    degreeLabel: 'Degree',
    fullChartNote:
      'This table shows only the astrological calculations. Life-impact narrative is added by the AI layer in a later phase (Phase 13).',
    dashaTitle: 'Vimshottari Dasha',
    currentDashaLabel: 'Current Dasha',
    mahadashaLabel: 'Mahadasha',
    antardashaLabel: 'Antardasha (Bukti)',
    pratyantardashaLabel: 'Pratyantardasha',
    previousMahadashaLabel: 'Previous Mahadasha',
    nextMahadashaLabel: 'Next Mahadasha',
    mahadashaTimelineTitle: 'Mahadasha Timeline',
    toLabel: 'to',
    transitTitle: 'Transit (Gochara)',
    transitNote: "This reflects today's transit position — distinct from the permanent results of the natal chart.",
    transitGrahaCol: 'Graha',
    transitSignCol: 'Sign',
    houseFromMoonCol: 'House from Moon',
    houseFromLagnaCol: 'House from Lagna',
    sadeSatiLabel: 'Sade Sati',
    sadeSatiPhase: {
      RISING: 'Rising phase',
      PEAK: 'Peak phase',
      SETTING: 'Setting phase',
    },
    sadeSatiInactive: 'Not currently applicable',
    ashtamaShaniLabel: 'Ashtama Shani',
    janmaShaniLabel: 'Janma Shani',
    yesLabel: 'Yes',
    noLabel: 'No',
    yogaTitle: 'Notable Yogas',
    noYogasFound: 'None of the tracked yogas were detected in this chart.',
    yogaStrength: {
      LOW: 'Mild',
      MODERATE: 'Moderate',
      STRONG: 'Strong',
    },
    yogaPlanetsLabel: 'Grahas',
    yogaHousesLabel: 'Houses',
    doshaTitle: 'Doshas',
    doshaIntro:
      "The items below are configurations identified using traditional astrological rules. They are not fixed verdicts — for matchmaking or remedies, consult a qualified astrologer.",
    noDoshasFound: 'None of the tracked doshas were detected in this chart.',
    doshaSeverity: {
      LOW: 'Mild',
      MODERATE: 'Moderate',
      STRONG: 'Strong',
    },
    doshaRuleLabel: 'Rule detected',
    houseAnalysisTitle: 'Analysis of the 12 Houses',
    houseCol: 'House',
    signCol: 'Sign',
    significationCol: 'Signifies',
    lordCol: 'Lord',
    occupantsCol: 'Grahas',
    aspectsCol: 'Aspects',
    influenceCol: 'Benefic / Malefic',
    strengthCol: 'Strength',
    conjunctionTag: 'Conjunction',
    none: '—',
    beneficShort: 'Benefic',
    maleficShort: 'Malefic',
    createAnother: 'Create another Jathakam',
    requiredField: 'This field is required',
    error: 'Error',
    predictionTitle: 'AI Interpretation',
    predictionSectionNames: {
      basic_reading: 'Chart Summary',
      health: 'Health',
      wealth: 'Wealth and Finances',
      career: 'Career',
      marriage: 'Marriage and Partnership',
      karma: 'Karma and Spiritual Trend',
      future: 'Upcoming Trend',
      graha_phalan: 'Planetary Results',
      past_life: 'Past Life Overview',
      present_life: 'Present Life Stage',
      business: 'Business',
      family: 'Family',
      children: 'Children',
      education: 'Education',
      foreign_travel: 'Foreign Travel',
      property: 'Property',
      favorable_periods: 'Favorable Periods',
      favorable_days: 'Favorable Days',
      favorable_colors: 'Favorable Colors',
      favorable_numbers: 'Favorable Numbers',
      remedies: 'Remedies',
      life_timeline: 'Key Life Timeline',
      final_summary: 'Final Summary',
    },
    generateButton: 'Get AI Interpretation',
    regenerateButton: 'Regenerate',
    generating: 'Generating... (this may take a moment)',
    predictionConfidenceLabel: 'Confidence',
    predictionConfidence: {
      HIGH: 'High',
      MEDIUM: 'Medium',
      LOW: 'Low',
    },
    palanPeriodLabel: 'Period to predict for',
    palanPeriodMode: {
      CURRENT: 'Current dasha/bukti only',
      NEXT_YEARS: 'Next N years',
      WHOLE_LIFE: 'Whole life',
      UNTIL_DASHA: 'Until a specific dasha',
    },
    palanPeriodYearsLabel: 'Years',
    palanPeriodUntilMahadashaLabel: 'Until this Mahadasha',
    palanPeriodUntilAntardashaLabel: 'Until this Antardasha (optional)',
    palanPeriodUntilAntardashaAny: 'Whole Mahadasha',
    reportStructureTitle: 'Report Structure (34 sections)',
    reportStructureNote: 'Every Jathakam report follows this 34-section structure (still being built out).',
    reportStatus: {
      chart_data: 'Calculated',
      ai_generated: 'AI generated',
      ai_pending: 'AI interpretation not yet generated',
      unavailable: 'Coming soon',
    },
    loadingReport: 'Loading report structure...',
    pdfTitle: 'PDF Report',
    pdfDownloadButton: 'Download PDF',
    pdfGenerating: 'Generating PDF... (this may take a moment)',
    pdfNote: 'The PDF only includes AI interpretations generated so far. Regenerate above, then download a fresh PDF, to include more.',
    pdfEmailButton: 'Email me this PDF',
    pdfEmailSending: 'Sending...',
    pdfEmailSent: 'Sent',
    myChartsTitle: 'My Charts',
    noChartsYet: "You haven't created any charts yet.",
    createFirstChartButton: 'Create your first chart',
    viewChartButton: 'View chart',
    loadingCharts: 'Loading your charts...',
    bornOnLabel: 'Born',
    backToDashboard: 'Back to home',
    loadingChart: 'Loading chart...',
    overviewTab: 'Overview',
    housesTab: 'Houses',
    yogasTab: 'Yogas & Doshas',
    aiTab: 'AI Interpretation',
    chartDetailsTitle: 'Chart Details',
    downloadPdfAction: 'PDF Report',
    settingsTitle: 'Settings',
    settingsAccountSection: 'Account',
    settingsEmailLabel: 'Email',
    settingsRoleLabel: 'Role',
    settingsPlanLabel: 'Plan',
    settingsLanguageSection: 'Default Language',
    settingsLanguageNote: 'The language shown by default on this device.',
    settingsLogoutButton: 'Log out',
    settingsDangerZone: 'Danger Zone',
    settingsDeleteAccountButton: 'Permanently delete account',
    settingsDeleteAccountNote: 'This permanently deletes all your charts, reports, and account data.',
    settingsDeleteConfirmPrompt: 'Are you sure you want to delete your account? This cannot be undone.',
    settingsDeleting: 'Deleting...',
    settingsBackToDashboard: 'Back to home',
    askAiTitle: 'Ask Your Chart',
    askAiLanguageLabel: 'Answer language',
    askAiPlaceholder: 'e.g. When will I go abroad? When will I get married?',
    askAiSubmit: 'Ask',
    askAiAsking: 'Thinking...',
    askAiEmpty: 'Ask anything about your chart — the answer is grounded only in this chart’s calculated data.',
    askAiHistoryTitle: 'Previous questions',
  },
} as const;
